### ISSUE TITLE
Installer failed security check - Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by ghost** [AClark-WHONET/AMRIE#1]
Installer failed security check while submitting package for WinGet - Windows Package Manager Community Repository.

https://github.com/microsoft/winget-pkgs/pull/132123

![image](https://github.com/AClark-WHONET/AMRIE/assets/154745174/9cc86b60-6d39-4730-815b-fd824d4db31b)

**Comment by AClark-WHONET** [comment]
Thanks @drshtmstry for opening a ticket with winget about this issue.

**Comment by AClark-WHONET** [comment]
Microsoft has confirmed that this was an error on their side and corrected the issue.
